/**
 * Protocol and Framing Error Codes.
 */

export const ProtocolErrorCode = {
  ERR_PROTOCOL: 'ERR_PROTOCOL',
  ERR_INVALID_JSON: 'ERR_INVALID_JSON',
  ERR_INVALID_ENVELOPE_TYPE: 'ERR_INVALID_ENVELOPE_TYPE',
  ERR_INVALID_MSG_ID: 'ERR_INVALID_MSG_ID',
  ERR_INVALID_CORR_ID: 'ERR_INVALID_CORR_ID',
  ERR_INVALID_T_MONO_NS: 'ERR_INVALID_T_MONO_NS',
  ERR_INVALID_T_WALL_MS: 'ERR_INVALID_T_WALL_MS',
  ERR_INVALID_KIND: 'ERR_INVALID_KIND',
  ERR_INVALID_TOPIC: 'ERR_INVALID_TOPIC',
  ERR_INVALID_SEQ: 'ERR_INVALID_SEQ',
  ERR_MISSING_PAYLOAD: 'ERR_MISSING_PAYLOAD',
  ERR_INVALID_IDEM_KEY: 'ERR_INVALID_IDEM_KEY',
  ERR_INVALID_EXPIRES_AT: 'ERR_INVALID_EXPIRES_AT',
  ERR_ENCODE_FAILED: 'ERR_ENCODE_FAILED',
  ERR_UNKNOWN_PARSE: 'ERR_UNKNOWN_PARSE',
  ERR_AUTH_FAILED: 'ERR_AUTH_FAILED',
  ERR_TIMEOUT: 'ERR_TIMEOUT',
} as const;

export type ProtocolErrorCode = (typeof ProtocolErrorCode)[keyof typeof ProtocolErrorCode];
